# Generated by Django 4.1.3 on 2024-08-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0002_purchasepayment_salepayment_remove_refund_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='transaction',
        ),
        migrations.AddField(
            model_name='refund',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='refund',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
