# Generated by Django 4.1.3 on 2024-08-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_refund_transaction_refund_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('RETURNED_GOODS', 'Returned Goods'), ('CANCELLED_ORDER', 'Cancelled Order'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(default='No description provided')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.purchasepayment')),
            ],
        ),
        migrations.CreateModel(
            name='SaleRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('RETURNED_GOODS', 'Returned Goods'), ('CANCELLED_ORDER', 'Cancelled Order'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(default='No description provided')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.salepayment')),
            ],
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
