# Generated by Django 4.1.3 on 2024-08-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_materialinvoice_unit_price'),
        ('customers', '0001_initial'),
        ('payments', '0004_purchaserefund_salerefund_delete_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Customerbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
