# Generated by Django 4.1.3 on 2024-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_vendorbalance_customerbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('net_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
