# Generated by Django 4.1.3 on 2024-08-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rawproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
