# Generated by Django 4.1.3 on 2024-08-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
