# Generated by Django 4.1.3 on 2024-08-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
