# Generated by Django 4.1.3 on 2024-08-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_material_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
