# Generated by Django 4.1.3 on 2024-08-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_material_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='vat_material',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
