# Generated by Django 4.1.3 on 2024-08-24 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseitem_remove_purchaseorderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendor', to='purchases.vendor'),
        ),
    ]
