# Generated by Django 4.1.3 on 2024-08-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchaseinvoice_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('commercial_register', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('vendors_code', models.CharField(max_length=20, unique=True)),
                ('vendors_logo', models.ImageField(blank=True, null=True, upload_to='vendors_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='material',
            field=models.CharField(default='Default Material', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchases.vendors'),
        ),
    ]
