# Generated by Django 4.1.3 on 2024-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_materialinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinvoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
