# Generated by Django 4.1.3 on 2024-08-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_price_per_unit'),
        ('inventory', '0004_remove_warehouse_location_warehouse_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rawproduct'),
        ),
    ]
