# Generated by Django 4.1.3 on 2024-08-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_finishedproduct'),
        ('inventory', '0005_alter_inventorymovement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct'),
        ),
    ]
