# Generated by Django 4.1.3 on 2024-08-23 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_finishedproduct'),
        ('inventory', '0007_remove_inventorymovement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct'),
            preserve_default=False,
        ),
    ]
