# Generated by Django 4.1.3 on 2024-08-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorymovement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='usewarehouse'),
        ),
    ]
