# Generated by Django 4.1.3 on 2024-08-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_price_per_unit'),
        ('products', '0004_finishedproduct'),
        ('inventory', '0012_alter_inventorymovement_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.rawproduct'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
