# Generated by Django 4.1.3 on 2024-08-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_inventoryreport_paymentreport_purchasereport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesReport',
            new_name='SalesReportView',
        ),
    ]
