# Generated by Django 4.1.3 on 2024-08-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_salesreport_salesreportview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreport',
            old_name='total_purchase_payments',
            new_name='net_payments',
        ),
        migrations.RemoveField(
            model_name='paymentreport',
            name='total_sale_payments',
        ),
    ]
