# Generated by Django 4.1.3 on 2024-08-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventorymovement_warehouse_delete_inventory_and_more'),
        ('products', '0002_material_delete_seasoning_and_more'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturing_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.manufacturingprocess')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturingprocess',
            name='raw_materials_used',
            field=models.ManyToManyField(through='manufacturing.MaterialUsage', to='materials.material'),
        ),
        migrations.AddField(
            model_name='manufacturingprocess',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_warehouse', to='inventory.warehouse'),
        ),
    ]
