# Generated by Django 4.1.3 on 2024-08-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rawproduct'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rawproduct'),
        ),
    ]
