# Generated by Django 4.1.3 on 2024-08-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_alter_manufacturingprocess_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingprocess',
            name='final_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
