# Generated by Django 4.1.3 on 2024-08-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_finishedproduct'),
        ('customers', '0001_initial'),
        ('sales', '0002_alter_salesinvoiceitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='finished_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='vat_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.DeleteModel(
            name='SalesInvoiceItem',
        ),
    ]
