# Generated by Django 4.1.3 on 2024-08-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0004_finishedproduct'),
        ('sales', '0003_remove_salesinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct'),
        ),
    ]
