# Generated by Django 4.1.3 on 2024-08-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('orders', '0001_initial'),
        ('purchases', '0002_vendor_remove_purchaseorder_customer_and_more'),
        ('sales', '0001_initial'),
        ('inventory', '0002_inventorymovement_warehouse_delete_inventory_and_more'),
        ('products', '0002_material_delete_seasoning_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ManufacturedProduct',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
